name: Build and Test - Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest

    steps:
    - uses : actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: "2.0.1"
        channel: "stable"

    - name: Build Application
      run: flutter pub get
    
    - name: Execute Test
      run: flutter test --coverage